### ISSUE TITLE
doesn't start ubuntu

### ISSUE THREAD

**Issue by bogdandudu** [kaiserdj/Darkorbit-client#26]
it might be offtopic and not a real issue
it show loading but stucked
![Screenshot from 2021-05-27 12-07-54](https://user-images.githubusercontent.com/20356046/119798940-48e94480-bee4-11eb-8652-4b339ee21c1d.png)
i run it on ubuntu with npm , it works with windows virtualbox exe client.
is that any way to clear cache on ubuntu for this? and make it run

**Comment by BenjaminEmiliani** [comment]
Same on Mac

**Comment by kaiserdj** [comment]
I just published an update with a new option to clear cache, I hope this will solve your problem. https://github.com/kaiserdj/Darkorbit-client/releases/tag/v2.2.1

You can also delete the client data, deleting the darkorbit-client folder that is located in AppData / Roaming

I'm sorry I was late in updating the application, lately I am very busy

**Comment by kaiserdj** [comment]
I close the issue, if you have problems again please open it again

**Comment by bogdandudu** [comment]
I have updated , git pull and npm install ... i have clicked clear cache several times , reloading, but stuck in the same place, also downloaded .zip file same issue . Thank you.
![Screenshot from 2021-05-28 16-03-34](https://user-images.githubusercontent.com/20356046/119988399-c12c3480-bfce-11eb-95a8-f503640b9492.png)

**Comment by kaiserdj** [comment]
You´re welcome, I am glad that it already works correctly ❤️

**Comment by BenjaminEmiliani** [comment]
For those that the update still does not work. Using the clear cache button did not fix the problem for me. I had to manually delete the cached files for the darkorbit-client. 

As Kaiser mentioned "You can also delete the client data, deleting the darkorbit-client folder that is located in AppData / Roaming". I'm on mac so I had to go to ~/Library/Application Support    and delete the darkorbit-client folder in there.

**Comment by maksimka5367** [comment]
did the game start after deleting?

**Comment by kaiserdj** [comment]
I think that the people who had problems before, the problem was solved
